### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [flathub/com.musixmatch.Musixmatch#3]
Info: org.freedesktop.Platform//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.musixmatch.Musixmatch

**Comment by hfiguiere** [comment]
closed with #2
