### ISSUE TITLE
The app can not detect running spotify

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [flathub/com.musixmatch.Musixmatch#4]
The app shows an "open spotify" forever when spotify (also the flatpak version) is already running. It had the same issue before but from time to time it would work after a few more songs playing. Now it's forever asking me to "open spotify". If I click it spotify would just stop playing songs like it's just been launched. Then musixmatch still shows me "open spotify" after I start to play songs.

**Comment by bbhtt** [comment]
Can you please test https://github.com/flathub/com.musixmatch.Musixmatch/pull/371?

Seems to work fine for me.

Both are installed as flatpaks

[0834f8d89d.webm](https://github.com/flathub/com.musixmatch.Musixmatch/assets/62639087/1f73b85c-3bef-4148-a3c5-17bba2c677ff)

**Comment by bbhtt** [comment]
Not sure if anything can be done here. It seems to be an issue with the app outside of flatpak too. And with the app being discontinued I don't think this can be solved. 

But if you have spotify running already and playing songs, you can launch musixmatch -> click open spotify -> new spotify window replaces old one -> click play again in spotify window -> song is correctly detected.

Please ping or reopen, if this is not the case/doesn't work. Thanks.
