### ISSUE TITLE
Musixmatch 3.10 fails to install for wrong size check

### ISSUE THREAD

**Issue by abecerra** [flathub/com.musixmatch.Musixmatch#7]
Looking for matches?

com.musixmatch.Musixmatch permissions:
    ipc           network      x11     dri     dbus access [1]
    tags [2]

    [1] org.freedesktop.Notifications, org.kde.StatusNotifierWatcher
    [2] proprietary

        ID                                  Branch          Op          Remote           Download
 1. [\] com.musixmatch.Musixmatch           stable          i           flathub          27.5?kB / 1.2?MB

Installing? ???????????????????? 100%
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat 'musixmatch-*': No such file or directory
        ID                                  Branch          Op          Remote           Download
 1. [?] com.musixmatch.Musixmatch           stable          i           flathub          27.5?kB / 1.2?MB

Error: While trying to apply extra data: apply_extra script failed, exit status 256
error: Failed to install com.musixmatch.Musixmatch: While trying to apply extra data: apply_extra script failed, exit status 256

**Comment by bbhtt** [comment]
Please test https://github.com/flathub/com.musixmatch.Musixmatch/pull/371
